project:
  type: website

website:
  title: "Tony_Zhu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "Â© 2026 Jingchao (Tony) Zhu"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/
      - icon: github
        href: https://github.com/TonyZhu233

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto

